### ISSUE TITLE
fatal: destination path '.' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by wandl** [ezekg/theme-juice-cli#43]
If you try and install to an existing empty directory by typing full path:

• Where do you want to setup the project? : (/Users/<user>/) /Users/<user>/Sites/<project>
theme-juice will fail:
 … Cloning theme
fatal: destination path '.' already exists and is not an empty directory.

I think it should at least be more clear to actually cd ~/<user>/<sites> then run theme-juice and only specify the folder name to create if it exists then maybe ask what to do eg: run anway?

This had me stumped at first.

**Comment by ezekg** [comment]
I guess I had never tried passing in absolute paths. I can't believe I didn't have any tests for this. Just pushed out a new version with the patch. Thanks for the report! :+1:
