### ISSUE TITLE
Allow creation of custom Capistrano tasks

### ISSUE THREAD

**Issue by ezekg** [ezekg/theme-juice-cli#62]
We can keep those tasks within a directory like `deploy/tasks/` and load them in [from here](https://github.com/ezekg/theme-juice-cli/blob/master/lib/theme-juice/tasks/load.rb?ts=2#L28-L35). :+1:

**Comment by cycomarcooo** [comment]
It would be a great place to override the builtin db:push task by a more power-full one using [Peach](https://github.com/petesaia/Peach), [Migrate db](https://github.com/deliciousbrains/wp-migrate-db) or its clone [wp-sync-db-cli](https://github.com/wp-sync-db/wp-sync-db-cli) :+1:

**Comment by ezekg** [comment]
@cycomarcooo https://github.com/ezekg/theme-juice-cli#can-i-define-my-own-capistrano-tasks. 👍
