### ISSUE TITLE
macOS 10.13: Bad Interpreter 

### ISSUE THREAD

**Issue by rtvenge** [ezekg/theme-juice-cli#79]
I upgraded to High Sierra on a non-critical machine to test things out and it looks like Apple upgraded Ruby to 2.3.

```
$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
```

When trying to run the `tj` command, I'm getting a ruby error. It appears its looking for the wrong version of Ruby.

```
$ tj
zsh: /usr/local/bin/tj: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin: no such file or directory
```

Anything I can fix on my end or does this require a patch?

Thanks!

**Comment by ezekg** [comment]
Try reinstalling `gem install theme-juice`.

**Comment by rtvenge** [comment]
Yeah, I had tried that as well, but was getting permission errors:

```
gem install theme-juice
Fetching: thor-0.19.4.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
```

For kicks, I tried `sudo`:

```
sudo gem install theme-juice
Password:
Fetching: thor-0.19.4.gem (100%)
Successfully installed thor-0.19.4
Fetching: i18n-0.8.6.gem (100%)
Successfully installed i18n-0.8.6
Fetching: faker-1.4.3.gem (100%)
Successfully installed faker-1.4.3
Fetching: os-0.9.6.gem (100%)
Successfully installed os-0.9.6
Fetching: net-ssh-2.9.4.gem (100%)
Successfully installed net-ssh-2.9.4
Fetching: net-scp-1.2.1.gem (100%)
Successfully installed net-scp-1.2.1
Fetching: sshkit-1.14.0.gem (100%)
Successfully installed sshkit-1.14.0
Fetching: capistrano-3.4.1.gem (100%)
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
```

Do you have to specify a path for the gem to install to? I know macOS protects some of the core file structure.

**Comment by ezekg** [comment]
This isn't an issue with the `theme-juice` gem, since [CocoaPods also had a similar issue filed](https://github.com/CocoaPods/CocoaPods/issues/6778). Very likely that High Sierra broke installed third-party gems using the system's Ruby. I would try installing [rvm](https://rvm.io/) and setting up your Ruby environment using that, which will avoid Apple breaking your Ruby like this in the future (since it won't depend on the system Ruby).

```
curl -L https://get.rvm.io | bash -s stable --ruby
```

Everything works fine on my end using rvm and High Sierra.

**Comment by ezekg** [comment]
Also, if you don't want to install `rvm`, may want to try:

```
gem install -n /usr/local/bin theme-juice
```

**Comment by rtvenge** [comment]
Thanks! I think a lot of this stemmed from the fact that I didn't have Xcode updated. After I upgraded that, things started falling into place.

I did end up installing rvm, I might not have had to. Can't hurt though. 

Thanks again! 😀

**Comment by ezekg** [comment]
Awesome. No problem! 🙂
